apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudnative-lab

resources:
  - ../../k8s/base/namespace.yaml
  - ../../k8s/base/api-configmap.yaml
  - ../../k8s/base/api-secret.yaml
  - ../../k8s/base/api-deployment.yaml
  - ../../k8s/base/api-service.yaml
  - ../../k8s/base/web-deployment.yaml
  - ../../k8s/base/web-service.yaml
  - ../../k8s/base/redis.yaml
