apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: cloudnative-lab
spec:
  type: NodePort
  selector:
    app: demo-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080